name: Create and publish dev docker images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-push-image:
    uses: kir-dev/workflows/.github/workflows/docker-publish.yml@main
    with: {}

